"""Golden-vector and parity tests for the BlueWallet ISAAC PoC.

The vectors below are pinned against the historical writeup and independently
confirmed against Node running the real ``isaac@0.0.5`` package.
"""

import os
import sys

import pytest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from bluewallet_isaac import (  # noqa: E402
    Isaac,
    bluewallet_v3_entropy_hex,
    bluewallet_v3_singlekey_priv,
    create_hd_wallet,
    create_singlekey_wallet,
    isaac_32_bytes_hex,
)
from bluewallet_isaac import attack  # noqa: E402
from bluewallet_isaac import bitcoin  # noqa: E402

# seed -> (raw 32-byte draw hex, HD entropy hex, single-key priv hex),
# generated by Node + isaac@0.0.5 (see docs/EXPLOIT.md and /tmp parity harness).
JS_PARITY = {
    1: ("cb8d04d22eacc7c3f2c1c338b00226106f192e7358f61e741d844e4be89b6e1f",
        "2132c5907cbc79a7787eee988a67ef7342d7e4b4083faba7e1e468c92b4b0aa2",
        "f7b794d0944c9fd8c8e1b50433ef38609fd0d46f9bc10badeaaada8fedb30646"),
    2: ("4e7cc380a642ca07b4c7f1584fdf8ca42f2a1c9ed5b7bdade9ddfa1ba0b02934",
        "0d49c54a1da3bfdcfea15fbf12d4b1dc75c916878a924c437a2c2ac464cf53ee",
        "1f5c289f78b4a61aeae97f62232e011ed5a55e9b9aa90530d1d5f75ee271dc10"),
    3: ("d2145b36d897b70f032f67f2c3dbcc81427817755c14afa56f5889b5ff24ca67",
        "05bf4c724e7d51a942b69f1baf2d1a28cbfec11c9b564bd0582ec328dc2445b5",
        "8d43b63a3e8a74ede407a510f96e30eb8020e92925cd4b6d17b7bbe29c4655fb"),
    42: ("e48f7bc96c5ea3f3e8136b0d933a80513b5eea2f54b197c038c8c7ce825833d3",
         "a8553bdcb2bc20e74e0dbea6d8e73ed05302d4530183f2475a06d036248594ac",
         "01f7c2b2ebd8d325adb518923bcccffedd796a335769954d23a3285eace5a787"),
    123456789: ("1bbac944dcc9f66aa7b6a35dd71d7c3123768540cc0a705cef9168b98f492249",
                 "9c58db3ee300ecfc1515df08a51fb7032d9651b8d7ecff84dd244ea9881ebe12",
                 "597248644205af5e7b8666732bbacd925bfb7bbeb4b363e2c916e56858ca6de0"),
    2147483647: ("a29c698fb53830204f48b0f16a5af114c6ac52f49ceb941a212133fe55426fac",
                 "393f194be2283f27b7ec0162b58acd3ca89a4f1ac48a0c7993333337704bb142",
                 "6863b194ee7be089fb0e2cfa20286969dcc2e4b47353583a92238df2c8bc9bb9"),
    4000000000: ("25b6a8a8fc52b75cdcdaa375403d5f7cd6d1342c13525df3aa920111dd16a7ee",
                 "c2045731d207e1ce612f22ca3e9c9472565658b67c167a7f474f787fe129969e",
                 "d4c04665eefb8789ba62b90e190440dcf7eef478dd52923e2ce8dab622e96a8b"),
    4294967295: ("88a6a3757f8872fb904218d51045fde5d86fe2eff282d4bd4d3fe6b115b30bb9",
                 "c9cf633cbf2d2f49801f9b8d96a64a7e016c3dfea40bd370b9572e27229af19d",
                 "04dfaa53c392aab8b50f729cf0d8ebe18dd0daa3e912065f4466793c03c7779d"),
}


@pytest.mark.parametrize("seed,expected", JS_PARITY.items())
def test_js_parity(seed, expected):
    raw, hd_entropy, sk_priv = expected
    assert isaac_32_bytes_hex(seed) == raw
    assert bluewallet_v3_entropy_hex(seed) == hd_entropy
    assert bluewallet_v3_singlekey_priv(seed).hex() == sk_priv


def test_seed0_models_reachable_float_space():
    # Real auto-seed uses a truthy float; integer-part 0 must go via the array
    # path, matching Node's seed(0.7)/seed(0.999) (not the falsy seed(0) path).
    assert isaac_32_bytes_hex(0) == "98b0b030a919338fdfd2094c16b4492645e23aa574da2c968072e785c446c704"


def test_golden_addresses_seed1():
    hd = create_hd_wallet(1)
    assert hd.mnemonic == (
        "cancel normal goat west shy squirrel tiger tape obtain farm wink track "
        "coin venture south among produce disease jungle spice naive pitch clever flight"
    )
    assert hd.bip49_address(0) == "37D7efZUJ5S1BdiS63EKX4nAGbSJ1UpBYQ"
    assert hd.bip49_privkey_hex(0) == "12df08697cbf22dc5f9b74801c7325ccb78cb18f0825029f44288c2f024ddc96"

    sk = create_singlekey_wallet(1)
    assert sk.segwit_p2sh_address() == "35mpjXaH4oRMAzSzbMRiNgjwmXtaSVMZA8"


def test_isaac_random_range():
    rng = Isaac().seed(12345)
    for _ in range(1000):
        v = rng.random()
        assert 0.0 <= v < 1.0


def test_bitcoin_primitives_known_vector():
    # priv=1 -> well-known secp256k1 pubkey and addresses.
    priv = (1).to_bytes(32, "big")
    pub = bitcoin.privkey_to_pubkey(priv, compressed=True)
    assert pub.hex() == "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798"
    assert bitcoin.p2pkh_address(pub) == "1BgGZ9tcN4rm9KBzDn7KprQz87SZ26SAMH"
    assert bitcoin.wif_from_priv(priv) == "KwDiBf89QgGbjEhKnhXJuH7LrciVrZi3qYjgd9M7rFU73sVHnoWn"


def test_recover_roundtrip_singlekey():
    secret = 4242
    targets = set(attack.addresses_for_seed(secret, kinds=(attack.KIND_SEGWIT_P2SH,)).values())
    result = attack.recover_seed(targets, start=0, end=10000, kinds=(attack.KIND_SEGWIT_P2SH,))
    assert result.found
    assert result.seed == secret


def test_recover_roundtrip_bip49():
    secret = 777
    targets = set(attack.addresses_for_seed(secret, kinds=(attack.KIND_BIP49,), gaps=2).values())
    result = attack.recover_seed(targets, start=0, end=5000, kinds=(attack.KIND_BIP49,), gaps=2)
    assert result.found
    assert result.seed == secret
